def getData():
    global token,prompt
    token = entry_1.get()
    prompt = entry_2.get()
    '''
    print(email)
    print(password)
    print(token)
    print(prompt)'''
    main.getUserData(token,prompt)

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import main

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Hector\Documents\Code\Python\TkDesigner\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


jsonFile = "response.json"

with open(jsonFile, 'w') as f:
    pass

window = Tk()

window.geometry("480x800")
window.configure(bg = "#FFFFFF")
window.title("AI Presentations Thing")

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 800,
    width = 480,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    480.0,
    800.0,
    fill="#3461FD",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    240.0,
    515.0,
    image=image_image_1
)

canvas.create_text(
    75.0,
    316.0,
    anchor="nw",
    text="Replicate Token",
    fill="#3461FD",
    font=("IBMPlexSans Bold", 20 * -1)
)

canvas.create_text(
    75.0,
    470.0,
    anchor="nw",
    text="Prompt",
    fill="#3461FD",
    font=("IBMPlexSans Bold", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: getData(),
    relief="flat",
    bg = "white"
)
button_1.place(
    x=50.0,
    y=616.0,
    width=380.0,
    height=120.0
)

canvas.create_text(
    126.0,
    64.0,
    anchor="nw",
    text="Making presentations\nwith ChatGPT and Stable Diffusion",
    fill="#E7E7E7",
    font=("IBMPlexSans Medium", 20 * -1)
)

canvas.create_text(
    27.0,
    19.0,
    anchor="nw",
    text="AI Presentation",
    fill="#FFFFFF",
    font=("IBMPlexSans Bold", 36 * -1)
)

canvas.create_text(
    27.0,
    60.0,
    anchor="nw",
    text="Thing",
    fill="#FFFFFF",
    font=("IBMPlexSans Bold", 36 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    239.5,
    374.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#9AC2FE",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=87.0,
    y=348.0,
    width=305.0,
    height=50.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    239.5,
    527.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#9AC2FE",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=87.0,
    y=501.0,
    width=305.0,
    height=50.0
)

canvas.create_text(
    98.0,
    190.0,
    anchor="nw",
    text="Because Who Needs Creativity",
    fill="#3461FD",
    font=("IBMPlexSans SemiBold", 20 * -1)
)

canvas.create_text(
    133.0,
    218.0,
    anchor="nw",
    text="   When You Have AI",
    fill="#3461FD",
    font=("IBMPlexSans SemiBold", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
